### ISSUE TITLE
I don't understand what the branches we have are and mean.

### ISSUE THREAD

**Issue by adam-zethraeus** [js3d/acorn#5]
I don't understand what the branches we have are and mean.

Dave, could you fill this in a bit? https://github.com/vorporeal/acorn/wiki/Branch-Usage

**Comment by vorporeal** [comment]
Sure.  Those were basically personal working branches that I was syncing between my machines using this repository.  I'll make a personal fork of this repo and transition the branches over there.  I'll try to get to it tonight, if not, this weekend.

**Comment by vorporeal** [comment]
I suggest the main repo (at least for now) only have master and a development branch (next/latest/nightly).  Reviewed and approved code can be merged into the development branch, and we can cut "releases" to master.

**Comment by adam-zethraeus** [comment]
Sounds good. Also sounds like we'de be using bonafide pull requests from our own forks. (Is it easy to keep those synchronized with dev?). In which case it sounds like that _would_ end up a decent CR method.

**Comment by pbwilmot** [comment]
we can also do merges into master with git patches like a real open source
project :-p

On Thu, Dec 6, 2012 at 11:06 AM, Adam Zethraeus notifications@github.comwrote:

> Sounds good. Also sounds like we'de be using bonafide pull requests from
> our own forks. (Is it easy to keep those synchronized with dev?). In which
> case it sounds like that _would_ end up a decent CR method.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vorporeal/acorn/issues/5#issuecomment-11099005.

## 

Peter Wilmot

**Comment by vorporeal** [comment]
Adam, when you have 15 minutes, send me a message and we can quickly figure out how to deal with branches/repos/forking/pull requests.
